### PR TITLE
feat(query): allow custom query separator string

### PR DESCRIPTION
**Pull request by Guria**

### CODE REVIEW

**Comment by Guria** [comment]
cc @christianalfoni

**Comment by christianalfoni** [comment]
Looked through it, looks good! as you parse out hash before query. What is the background for doing this really? Can not see why you want to use something else then `?`? Just wondering :)

**Comment by Guria** [comment]
Feature request from user on Discord. He rewriting existing app, where hash sign was used for queries.Good thing is that queries was pretty simple and able to be parsed with urlon.

**Comment by christianalfoni** [comment]
Okay, cool, looks good to me :D

**Pull request merged**
