### PR TITLE
Add query string parsing

### PR DESCRIPTION
**Pull request by bfitch**
This pull adds query string parsing via the [qs library](https://github.com/hapijs/qs), which allows for parsing arrays and deeply nested keys into JS objects. Tests should now be green again. I think the rest is pretty straightforward! :smile:

### CODE REVIEW

**Comment by christianalfoni** [comment]
Awesome stuff, thanks @bfitch I will add your ass as contributor here, so you get some more access.

**Comment by idream3** [comment]
@christianalfoni lol, you said 'ass' :)

**Comment by christianalfoni** [comment]
ops, typo, fixed it ;-)

**Comment by bfitch** [comment]
Thanks @christianalfoni. Happy for my ass to contribute ;).

**Pull request merged**
